apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: middle
spec:
  hosts:
  - middle
  http:
  - route:
    - destination:
        host: middle
        subset: v1
      weight: 100
      headers:
        request:
          set:
            middleversion: "v1"
    - destination:
        host: middle
        subset: v2
      weight: 100
      headers:
        request:
          set:
            middleversion: "v2"
