apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sm-argo-rollout-p100ssl
  namespace: openshift-gitops
spec:
  destination:
    namespace: sm-argo-rollout-p100ssl
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: ./argo-rollout-p100ssl
    repoURL: gitea@code.private.opequon.net:demos/service-mesh-deployment.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
