apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: birdie
    app.kubernetes.io/component: birdie
    app.kubernetes.io/instance: birdie
  name: birdie
  namespace: sm-argo-rollout-percent
spec:
  host: birdie-sm-argo-rollout-percent.apps.ocp4.private.opequon.net
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: birdie
    weight: 100
  wildcardPolicy: None
