apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
    - sm-simple
    - sm-percent-routing
    - sm-header-based-routing
    - sm-label-based-routing

