apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-service-mesh-operator
  namespace: openshift-service-mesh-operator
spec:
  channel: stable
  name: servicemeshoperator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 
