apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
  labels:
    app: front
    app.kubernetes.io/component: front
    app.kubernetes.io/instance: front
    app.kubernetes.io/name: front
    app.kubernetes.io/part-of: front
  name: front
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: front
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: front
        deployment: front
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/gotest/smgoapp:latest
        env:
        - name: NEXT_HOP
          value: middle:8080
        imagePullPolicy: Always
        name: front
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
